### ISSUE TITLE
BSEC output is 0.00

### ISSUE THREAD

**Issue by kerryleith** [ckuehnel/newArduino#1]
Hi, thanks for putting this together, I think you beat Bosch to it!

I have two Nicla Sense ME's and can't get the BSEC data from either. Which BSEC version are you using 1.X or 2.0?

18:23:47.615 -> Nicla Sense ME as Environmental Sensor
18:23:47.615 -> 
18:23:47.615 -> Temperature: 29.4 °C
18:23:47.615 -> Humidity: 48 %rH
18:23:47.615 -> Pressure: 974 hPA
18:23:47.615 -> MOX Resistance: 16661 Ohm
18:23:47.653 -> iAQ: 0
18:23:47.653 -> eCO2: 0 ppm
18:23:47.653 -> bVOC: 0.000 ppm
18:23:47.653 -> BSEC: BSEC output values - iaq: 0   iaq_s: 0   b_voc_eq: 0.00   co2_eq: 0   accuracy: 0   comp_t: 29.38   comp_h: 48.20   comp_g: 0

**Comment by ckuehnel** [comment]
#define SENSOR_DATA_FIXED_LENGTH (30) in SensorTypes.h
